In [1]:
import numpy as np

In [ ]:
np.empty((2,2))

array([[4.61781312e-315, 0.00000000e+000],
       [6.60513630e-310, 2.57026842e+151]])

In [ ]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full((2,2),2)

array([[2, 2],
       [2, 2]])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
new_list=[1,2,3,4]
np.array(new_list)

array([1, 2, 3, 4])

In [ ]:
np.arange(10,49,)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.random.random(30)
a

array([0.84051616, 0.3995522 , 0.1321791 , 0.0761981 , 0.25022679,
       0.03628376, 0.52920005, 0.93251942, 0.83621141, 0.96218219,
       0.4712411 , 0.29253392, 0.56441751, 0.90677822, 0.19796285,
       0.60216802, 0.56488212, 0.11500268, 0.80655243, 0.14776286,
       0.45478509, 0.67511291, 0.13205801, 0.15393381, 0.05522279,
       0.44463087, 0.05242416, 0.52106196, 0.04764372, 0.57448349])

In [ ]:
a=np.random.randint(100,size=(10,10))
a

array([[ 1, 51, 90, 93, 45, 81, 42, 79, 33, 44],
       [83, 86, 48, 36, 75, 97, 20, 15, 10, 52],
       [50, 48, 38, 65,  9, 58, 46, 64, 12, 97],
       [42, 52, 25, 77, 10, 19, 69,  6, 45, 38],
       [28,  6, 43, 72, 50, 79, 56, 57, 63, 68],
       [82, 40, 33, 10,  5, 62, 78, 86, 64, 91],
       [69, 14, 24, 50, 29, 11, 84, 65, 23, 60],
       [60, 83, 87, 10, 46, 91, 48, 95, 77, 24],
       [ 3, 35, 26, 97, 32,  9, 63, 76, 40, 68],
       [ 4, 53, 73, 49, 68, 23, 31, 88, 84, 36]])

In [ ]:
a.min()


np.int64(1)

In [ ]:
a.max()

np.int64(97)

In [ ]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
arr = [1,2,0,0,4,0]
r=np.array(arr)
np.flip(r)

array([0, 4, 0, 0, 2, 1])

In [ ]:
c=np.zeros((5,5),dtype=int)
c[0,:]=1
c[-1,:]=1
c[:,0]=1
c[:,-1]=1
c

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
c=np.ones((8,8),dtype=int)
c[1::2, ::2]=0
c[::2, 1::2]=0
c

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(x+y)

[[ 6  8]
 [10 13]]


In [ ]:
v = np.array([9,10])
w = np.array([11,12])
print(v+w)


[20 22]


In [ ]:
print(x-y)
print()
print(v-w)

[[-4 -4]
 [-4 -3]]

[-2 -2]


In [ ]:
print(3*x)
print()
print(3*y)
print()
print(3*v)
print()
print(3*w)

[[ 3  6]
 [ 9 15]]

[[15 18]
 [21 24]]

[27 30]

[33 36]


In [ ]:
print(x*x)
print()
print(y*y)
print()
print(v*v)
print()
print(w*w)
print()

[[ 1  4]
 [ 9 25]]

[[25 36]
 [49 64]]

[ 81 100]

[121 144]



In [ ]:
print(np.matmul(v,w))
print()
print(np.matmul(x,y))
print()
print(np.matmul(x,v))

219

[[19 22]
 [50 58]]

[29 77]


In [ ]:
np.vstack((x, y))

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((v, w))

array([ 9, 10, 11, 12])

In [ ]:
try:
    result = np.concatenate((x, v))
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
print(np.dot(A,A_inv))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
AB= np.dot(A,B)
BA= np.dot(B,A)
print(np.array_equal(AB,BA))

False


In [ ]:
AB_T = AB.T
BT_AT = np.dot(B.T,A.T)
print(np.array_equal(AB_T,BT_AT))

True


In [ ]:
coeff = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

inv_coeff = np.linalg.inv(coeff)
solution = np.dot(inv_coeff, constants)
list=["x","y","z"]
print(list)
print(solution)

['x', 'y', 'z']
[ 2.  1. -2.]


In [2]:
import time
A = np.arange(1000000)
B = np.arange(1000000)
start_time = time.time()
sum=A+B
time_taken = time.time() - start_time
print(time_taken)

0.0075609683990478516


In [4]:
start_t = time.time()
product=A*B
taken_t= time.time() - start_t
print(taken_t)

0.007547855377197266


In [5]:
start_time = time.time()
AB = np.dot(A,B)
time_taken = time.time() - start_time
print(time_taken)

0.0024099349975585938


In [6]:
start_time = time.time()
AB = np.matmul(A,B)
time_taken = time.time() - start_time
print(time_taken)

0.0067713260650634766
